on: issues
name: ✨ Create and move project cards
jobs:
  build:
    name: EricKuck/github-issues-to-projects
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: EricKuck/github-issues-to-projects
      uses: EricKuck/github-issues-to-projects@master
      env:
        GITHUB_TOKEN: "faketoken"
      with:
        args: Backlog Inbox "Up next"
